[package]
name = "libwl"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
mlua = { version = "0.8.0", default-features = false, features = ["luajit", "module"] }
