name: RADIUS dicitonaries validation
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: ./share/radius/
          yamllint_strict: true
          yamllint_comment: false
        
